server:
  port: 8787

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobile_banking_dev
    username: postgres
    password: Thearak97
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sothearakseng97@gmail.com
    password: pbaf eznw hehu nwhc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    property-naming-strategy: SNAKE_CASE

auth:
  jwt:
    secret: G7f9!2h@Lk8v#Jd4Px1Z&9MwRsYtUfQw
    expiration-ms: 3600000
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7
  otp:
    expiration-minutes: 5

rate:
  limiter:
    maxAttempts: 5
    blockDurationMinutes: 15

async:
  otp:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 50
  notification:
    corePoolSize: 3
    maxPoolSize: 6
    queueCapacity: 30
  resetPassword:
    corePoolSize: 3
    maxPoolSize: 6
    queueCapacity: 30
